// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_phd_RCPPEXPORTS_H_GEN_
#define RCPP_phd_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace phd {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("phd", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("phd", "_phd_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in phd");
            }
        }
    }

    inline NumericVector systematic_sample_cpp(int n_particles, NumericVector norm_weights) {
        typedef SEXP(*Ptr_systematic_sample_cpp)(SEXP,SEXP);
        static Ptr_systematic_sample_cpp p_systematic_sample_cpp = NULL;
        if (p_systematic_sample_cpp == NULL) {
            validateSignature("NumericVector(*systematic_sample_cpp)(int,NumericVector)");
            p_systematic_sample_cpp = (Ptr_systematic_sample_cpp)R_GetCCallable("phd", "_phd_systematic_sample_cpp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_systematic_sample_cpp(Shield<SEXP>(Rcpp::wrap(n_particles)), Shield<SEXP>(Rcpp::wrap(norm_weights)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_phd_RCPPEXPORTS_H_GEN_
